package net.jazdw.jnacan.c;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * CAN controller mode<br>
 * <i>native declaration : can/netlink.h:68</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class can_ctrlmode extends Structure {
	/** C type : __u32 */
	public int mask;
	/** C type : __u32 */
	public int flags;
	public can_ctrlmode() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("mask", "flags");
	}
	/**
	 * @param mask C type : __u32<br>
	 * @param flags C type : __u32
	 */
	public can_ctrlmode(int mask, int flags) {
		super();
		this.mask = mask;
		this.flags = flags;
	}
	public static class ByReference extends can_ctrlmode implements Structure.ByReference {
		
	};
	public static class ByValue extends can_ctrlmode implements Structure.ByValue {
		
	};
}
