package net.jazdw.jnacan.c;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : can/gw.h:57</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class cgw_csum_xor extends Structure {
	public byte from_idx;
	public byte to_idx;
	public byte result_idx;
	/** C type : __u8 */
	public byte init_xor_val;
	public cgw_csum_xor() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("from_idx", "to_idx", "result_idx", "init_xor_val");
	}
	/** @param init_xor_val C type : __u8 */
	public cgw_csum_xor(byte from_idx, byte to_idx, byte result_idx, byte init_xor_val) {
		super();
		this.from_idx = from_idx;
		this.to_idx = to_idx;
		this.result_idx = result_idx;
		this.init_xor_val = init_xor_val;
	}
	public static class ByReference extends cgw_csum_xor implements Structure.ByReference {
		
	};
	public static class ByValue extends cgw_csum_xor implements Structure.ByValue {
		
	};
}
