package net.jazdw.jnacan.c;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * CAN clock parameters<br>
 * <i>native declaration : can/netlink.h:40</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class can_clock extends Structure {
	/**
	 * CAN system clock frequency in Hz<br>
	 * C type : __u32
	 */
	public int freq;
	public can_clock() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("freq");
	}
	/**
	 * @param freq CAN system clock frequency in Hz<br>
	 * C type : __u32
	 */
	public can_clock(int freq) {
		super();
		this.freq = freq;
	}
	public static class ByReference extends can_clock implements Structure.ByReference {
		
	};
	public static class ByValue extends can_clock implements Structure.ByValue {
		
	};
}
