package net.jazdw.jnacan.c;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * CAN bus error counters<br>
 * <i>native declaration : can/netlink.h:60</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class can_berr_counter extends Structure {
	/** C type : __u16 */
	public short txerr;
	/** C type : __u16 */
	public short rxerr;
	public can_berr_counter() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("txerr", "rxerr");
	}
	/**
	 * @param txerr C type : __u16<br>
	 * @param rxerr C type : __u16
	 */
	public can_berr_counter(short txerr, short rxerr) {
		super();
		this.txerr = txerr;
		this.rxerr = rxerr;
	}
	public static class ByReference extends can_berr_counter implements Structure.ByReference {
		
	};
	public static class ByValue extends can_berr_counter implements Structure.ByValue {
		
	};
}
